server:
  port: 8077
  context-path: /sq

quartz:
  enabled: true
spring:
  thymeleaf:
    mode: LEGACYHTML5
  profiles:
     active: dev
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true

version:
  pcversion: "V1.1" # 版本号
  build: 1111 # 小版本号
