spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pdsw
    url: jdbc:mysql://172.20.50.115:3306/wh?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
#rabbitmq相关配置
#rabbitmq相关配置dell-PC
  rabbitmq:
    first:
       host: 172.20.50.115 #10.1.30.24 #10.1.3.202
       port: 5672
       username: siti #siti
       password: siti  #siti@sq
       publisher-confirms: true
       publisher-returns: true
       virtual-host: siti
       listener:
         simple:
           acknowledge-mode: manual #采用手动应答
           concurrency: 2
           max-concurrency: 2
           retry:
             enabled: true #是否支持重试
           prefetch: 1
    second:
     host: 114.80.231.178 #10.1.30.24
     port: 5671
     username: sq_dev
     password: 123456
     publisher-confirms: true
     publisher-returns: true
     virtual-host: sq_dev

  devstatusquene: quene-prod


logback:
  logHome: /sq_data/log/
  logName: sq


