spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.1.30.207:3306/wh?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
  redis:
    host: 10.1.30.129
    password: wh@siti
    port: 6379
    pool:
      max-active: 2000
      max-wait: 2000
      min-idle: 1
      max-idle: 100
#rabbitmq相关配置
  rabbitmq:
     host: 114.80.231.178 #10.1.30.24
     port: 5671
     username: shuiwen
     password: siti@sw
     publisher-confirms: true
     publisher-returns: true
     virtual-host: shuiwen
     listener:
        simple:
          acknowledge-mode: manual #采用手动应答
          concurrency: 2
          max-concurrency: 2
          retry:
            enabled: true #是否支持重试
          prefetch: 1

logback:
  logHome: wh/log/
  logName: wh
wh:
  #海康Appkey
  appKey: c725240706e4454bad75945b219ba0e5
  #安全秘钥
  appSecret: 528c2c2221b206c90861ce56a73d73bf
  #流畅视频接口
  fluencyEzopen: //open.ys7.com/D24409905/1.live
  #高清视频接口
  highDefinitionEzopen: //open.ys7.com/D24409905/1.hd.live


