spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://10.1.30.207:3306/wh?useUnicode=true&characterEncoding=utf8&useSSL=true&allowMultiQueries=true
#rabbitmq相关配置
  rabbitmq:
       host: 10.1.4.108 #10.1.30.24
       port: 5672
       username: wh
       password: wh@siti
       publisher-confirms: true
       publisher-returns: true
       listener:
          simple:
            acknowledge-mode: manual #采用手动应答
            concurrency: 2
            max-concurrency: 2
            retry:
              enabled: false #是否支持重试
            prefetch: 1
       virtual-host: /

logback:
  logHome: /sq_data/log/
  logName: sq


